### ISSUE TITLE
Explore the schema programmatically

### ISSUE THREAD

**Issue by EdVanDance** [DanielT/autosar-data-py#7]
Hello and merry Christmas to you 😃 

I have an use case where I would like to explore the schema of a specific AUTOSAR version programmatically.

Please correct me if I'm wrong ... it seems to be impossible to do so without creating a valid model as you go, since there is no interface exposed that allows to query for valid sub element types. There is `ElementType.find_sub_element(name, version)`, but I need an `Element` object to get a list of valid sub elements, which can't be created standalone, they have to be created within a proper context of the model.

Would you be willing to support this use case?

I think an "easy" option would be to allow Element object creation out of context. Then you could just query its properties. But that would be useless for any other use case and might be very confusing.

An other option would be to expose more ElementType interfaces I think. In addition to the already existing properties I would be interested in `content_type` and a possibility to get valid sub element types.

Is that feasible?

Regards,
Ed

**Comment by DanielT** [comment]
Thanks - merry Christmas!

The Rust-API for `ElementType` can already do that, but I didn't export all of the methods in the Python-API.
Exporting whatever is missing shouldn't be too difficult, I just didn't expect anyone to be interested.
You can see the full API that is used by the `autosar-data` parser here: [ElementType on docs.rs](https://docs.rs/autosar-data-specification/0.17.0/autosar_data_specification/struct.ElementType.html)

Comparatively it would be quite problematic to make a standalone `Element`, because then the invariant that all valid elements have a parent would be violated. That would break a lot of code.
